apiVersion: v1
kind: PersistentVolume
metadata:
  name: springboot-logs-nfs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: springboot-logs-nfs
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 172.31.10.90
    path: /srv/nfs/kubernetes/springboot-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springboot-logs
  namespace: bank-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: springboot-logs-nfs
  volumeName: springboot-logs-nfs-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-nfs
  namespace: bank-app
  labels:
    app: springboot-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-nfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springboot-nfs
    spec:
      nodeSelector:
        kubernetes.io/hostname: master-1
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: workload
          operator: Equal
          value: springboot
          effect: NoSchedule
      containers:
        - name: springboot
          image: local/springboot:nfs
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9024
          envFrom:
            - configMapRef:
                name: springboot-config
            - secretRef:
                name: springboot-secret
          env:
            - name: RELEASE_VERSION
              value: nfs-master1
            - name: LOGGING_FILE_PATH
              value: /var/log/springboot
            - name: LOGGING_FILE_NAME
              value: /var/log/springboot/springboot-nfs.log
          volumeMounts:
            - name: springboot-logs
              mountPath: /var/log/springboot
      volumes:
        - name: springboot-logs
          persistentVolumeClaim:
            claimName: springboot-logs
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-nfs-service
  namespace: bank-app
spec:
  type: ClusterIP
  selector:
    app: springboot-nfs
  ports:
    - name: http
      port: 9024
      targetPort: http
