apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-canary
  namespace: bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-canary
      track: canary
  template:
    metadata:
      labels:
        app: springboot-canary
        track: canary
    spec:
      containers:
        - name: springboot
          image: ratana/springboot:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9024
          envFrom:
            - configMapRef:
                name: springboot-config
            - secretRef:
                name: springboot-secret
          env:
            - name: RELEASE_VERSION
              value: "canary"
