apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-canary
  namespace: bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-canary
      track: canary
  template:
    metadata:
      labels:
        app: react-canary
        track: canary
    spec:
      containers:
        - name: react
          image: ratana/reactjs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: RELEASE_VERSION
              value: "canary"
