apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-config
  namespace: bank-app
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "mydb"
  DB_USER: "postgres"
