apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-green
  namespace: bank-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-bg
      version: green
  template:
    metadata:
      labels:
        app: react-bg
        version: green
    spec:
      containers:
        - name: react
          image: ratana/reactjs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: RELEASE_VERSION
              value: "green"
