deployment:
  replicas: 2

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
        topologyKey: kubernetes.io/hostname
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
updateStrategy:
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

ports:
  web:
    port: 8000
    hostPort: 80
    exposedPort: 80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    port: 8443
    hostPort: 443
    exposedPort: 443

service:
  spec:
    type: ClusterIP

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog:
  enabled: true