apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: bank-app
spec:
  selector:
    app: react-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
