appName:
  app: nginx-stagging
replicas: 2
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - worker
container:
  name: nginx-cont
  image: nginx:1.22.1
  port: 80 
  volumeMounts: 
  - name: my-spring-vol 
    mountPath: /app/src/main/resources/images
  volumes: 
  - name: my-spring-vol 
    persistentVolumeClaim: 
      claimName: spring-nfs-pvc-external
